### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by davibarreira** [zsteve/OptimalTransport.jl#13]
Hey there, I'm doing my dissertation on Optimal Transport, and will probably be writing some code in Julia. So I'm very interested in contributing. Do you have any guidelines on how to contribute?

Att,

**Comment by zsteve** [comment]
Hi Davi,
That would be great! Yes, I will add some information about contributing in the coming days.

Stephen

**Comment by davibarreira** [comment]
Cool, you added the logo! I'll be taking a look at your code in a couple of days, and probably will implement something by the weekend.

**Comment by zsteve** [comment]
Sounds good!

**Comment by zsteve** [comment]
P.S. if there are any suggestions about missing documentation/code not being clean, let me know. This evolved from some ad-hoc code written for my own projects, so it's still a work in progress :)
