### ISSUE TITLE
Move Python implementation to separate package?

### ISSUE THREAD

**Issue by devmotion** [zsteve/OptimalTransport.jl#18]
I ran into quite many problems when I tried to set up CI for a package that depended on OptimalTransport.jl due to the Python dependency and the requirement to install POT. I think it could be helpful to either make the Python dependency optional or move it to a separate package.

**Comment by zsteve** [comment]
Hi David,
Indeed I've had the same issue. I think making it optional would be a good idea; I'll look into incorporating this. I think currently the CI is broken for a related reason? (sorry I've been under the pump recently and haven't had much free time).

**Comment by devmotion** [comment]
> I think currently the CI is broken for a related reason?

I ended up with this CI setup: https://github.com/devmotion/CalibrationErrorsDistributions.jl/blob/master/.github/workflows/ci.yml Some parts are specific for my use case but I could submit a PR that updates the CI in a similar way here, if desired.
