### ISSUE TITLE
License

### ISSUE THREAD

**Issue by devmotion** [zsteve/OptimalTransport.jl#21]
I was very surprised when I just noticed that you use the GPL license for this package. Is there any particular reason for this? Commonly Julia packages use the MIT license since in contrast to GPL it is not viral and does not "infect" derivative work.

**Comment by zsteve** [comment]
Hi @devmotion ,
Sorry, this package was my first foray into the Julia ecosystem, so I wasn't aware of the norm.

I'm open to changing to the MIT license, although I suppose we will need the few other contributors so far to agree (shouldn't be much of a problem).
Let me know what you think.

**Comment by devmotion** [comment]
I would prefer if the license would be changed to MIT. I think it will increase the adaption of the package since some people just stay away from any GPL licensed packages and one has to be more cautious when looking at the code. See https://discourse.julialang.org/t/package-license/7109 and https://discourse.julialang.org/t/gpl-and-virality/7715 for some discussions around this topic.

**Comment by zsteve** [comment]
@davibarreira

**Comment by davibarreira** [comment]
I don't have much experience on this. So if @devmotion is saying so, I think we should probably change to MIT license.

**Comment by zsteve** [comment]
Ok done!
