### ISSUE TITLE
Documentation setup incorrect?

### ISSUE THREAD

**Issue by devmotion** [zsteve/OptimalTransport.jl#24]
It seems the documentation is not deployed correctly since the `gh-pages` branch does not exist. Maybe you did not add a deploy key and a secret to Github?

**Comment by devmotion** [comment]
I noticed that `deploydocs` is not called in `docs/make.jl`. This is fixed in https://github.com/zsteve/OptimalTransport.jl/pull/29.

**Comment by devmotion** [comment]
There seems to be an issue with the documenter key, see https://github.com/zsteve/OptimalTransport.jl/runs/1546479198#step:8:38:
```
Load key "/home/runner/work/OptimalTransport.jl/OptimalTransport.jl/docs/.documenter": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:zsteve/OptimalTransport.jl
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/6vUwN/src/Documenter.jl:552
```

**Comment by devmotion** [comment]
One can follow the steps in https://juliadocs.github.io/Documenter.jl/stable/man/hosting/walkthrough/#SSH-Deploy-Keys-Walkthrough to generate the keys, and then add the keys to Github.

**Comment by zsteve** [comment]
Thanks for the pointers (and the patience!) 
I'll take a look at this now :)

**Comment by zsteve** [comment]
Ok dev docs are up [here](https://zsteve.github.io/OptimalTransport.jl/dev). Stable docs will be up soon!

**Comment by devmotion** [comment]
Great, thanks a lot! The stable documentation will be available as soon as a new release is available in the package registry. Probably it would be good to update the link in the summary of the repo on Github.
