### ISSUE TITLE
Creating 1D Versions - Questions about Dependencies

### ISSUE THREAD

**Issue by davibarreira** [zsteve/OptimalTransport.jl#44]
Hey guys, I'm writing the 1D version for the Algorithms. Although our functions already work for the 1D case, I think we should implement a more efficient version, since the solution for the 1D case might be used on a future SlicedWasserstein (note that POT.py also has a 1D version).

My implementations use functions such as `quantile` from `Distributions.jl` and uses `quadgk` from `QuadGK.jl`.
**So I'd like your suggestion on making these two packages a dependency**. What do you think?
This would allow us use these two very neat functions for the 1D case:

```
function otc1d(μ::Distributions.UnivariateDistribution,ν::Distributions.UnivariateDistribution,c)
    g(μ,ν,x) = c(quantile(μ,x),quantile(ν,x))
    f(x) = g(μ,ν,x)
    return quadgk(f,0,1)[1]
end

function otp1d(μ::Distributions.UnivariateDistribution,ν::Distributions.UnivariateDistribution,c)
    Tmap(x) = Distributions.quantile(ν,Distributions.cdf(μ,x))
    return Tmap
end
```

Note that this allow us to calculate the distance for any 1D parametric distribution.

I've done some quick benchmarking, and the code seem quite efficient as is. Also, I think we should change the name of the functions `emd` and `emd2` to something more accurate, because they are not necessarily the Earth Movers Distance (but we can discuss this in another occasion).

Also, if we make `Distributions.jl` a dependency, we can multithread the `emd` function to accept `::Distributions.UnivariateDistribution.DiscreteNonParametric`.

**Comment by devmotion** [comment]
Isn't this correct only for specific cost functions `c(x, y)` of the form `c(x, y) = f(|x - y|)` where `f` is a convex function? I think I read that somewhere a while ago but maybe I don't remember it correctly.

Distributions already depends on QuadGK, so I guess the question is just if one wants to accept a dependency on Distributions. I would be fine with it.

For discrete 1D data where the histograms are of the same size and the cost function is of the special form above, probably it is more efficient though to just sort the values and not use `quadgk` (that's also what POT does: https://pythonot.github.io/_modules/ot/lp.html#emd_1d). So this possible efficiency improvement does not depend on Distributions.

**Comment by davibarreira** [comment]
Yeah! Sorry, I didn't write the whole story. You are right about the form of the cost function. It needs to be convex and symmetric for the formula I wrote.
So my idea is to implement different 1D functions, and one of them would be this one using the `Distribuitions.jl`, which would allow us to calculate, for example, the Wasserstein distance between a 1D Normal dist, and a 1D Gumbel (or whatever 1D distribution comes to mind).

**Comment by devmotion** [comment]
IMO as long as it is stated clearly in the documentation what `c` has to satisfy it is fine.

In general, I think [you should make `c` the first argument](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Write-functions-with-argument-ordering-similar-to-Julia-Base) and choose more descriptive names for the functions.

**Comment by davibarreira** [comment]
Thanks for the tips. I'll incorporate them and finish some missing functions. I'm reading the code from POT.py, and it looks like it only accepts convex functions, but in their case, they limit the cost function by a set of pre-defined distances. I'm actually looking an implementation that works for concave functions, so we can be more general.

**Comment by devmotion** [comment]
I think we should allow any function and make it the user's responsibility to ensure that it satisfies the required assumptions.

**Comment by davibarreira** [comment]
I agree. I'll write down the assumptions in the function doc.
