### ISSUE TITLE
Please add Fused Gromov Wasserstein

### ISSUE THREAD

**Issue by bionicles** [zsteve/OptimalTransport.jl#5]
Hi,

To compare huge molecules with different numbers of atoms, It would be great to have a way to do this:

https://tvayer.github.io/materials/Titouan_Marseille_2019.pdf

http://proceedings.mlr.press/v97/titouan19a.html

One problem we hit was, running out of GPU memory, it would be hella useful to do some blockwise reduction or something like that

**Comment by zsteve** [comment]
Hi bionicles,

Currently given the preliminary stage of this package, advanced algorithms such as those you cite are out of current project scope. 

However, if you'd like to implement such algorithms and contribute to the package, feel free :)

zsteve
